### ISSUE TITLE
The change of state_checked is not reflected only in API level 21

### ISSUE THREAD

**Issue by u-nation** [alexjlockwood/adp-delightful-details#15]
I'm suffering from a bug that occurs only in API level 21.
Do you have any ideas??

Please see the following gif for details.

|API level 21|API level 22|
|:--:|:--:|
|![api21_bug1](https://user-images.githubusercontent.com/4298012/38607584-05a751f8-3db4-11e8-9166-ca50b3ed15e1.gif)|![api22_bug1](https://user-images.githubusercontent.com/4298012/38607767-856fc438-3db4-11e8-90f8-85247d96bab6.gif)|
|![api21_bug2](https://user-images.githubusercontent.com/4298012/38607610-11a9d084-3db4-11e8-9f64-10984bb903bc.gif)|![api22_bug2](https://user-images.githubusercontent.com/4298012/38607937-f3a6a9da-3db4-11e8-8012-b46dfd7631e5.gif)|
|![api21_bug3](https://user-images.githubusercontent.com/4298012/38609371-d8a09ba6-3db8-11e8-8d75-8471caa4da69.gif)|![api22_bug3](https://user-images.githubusercontent.com/4298012/38609379-dd6cf3a0-3db8-11e8-9828-3cdb3472b38a.gif)|

**Comment by tendo-folio** [comment]
I found the solution.

Just add `android:background="?attr/selectableItemBackgroundBorderless"` , then works fine in every API level.

ripple drawable also works fine instead of `?attr/selectableItemBackgroundBorderless"`

For example
`android:background="@drawable/sample"`

```xml:sample.xml
<?xml version="1.0" encoding="utf-8"?>
<ripple xmlns:android="http://schemas.android.com/apk/res/android"
  android:color="#1effffff"
  />
```

https://github.com/dandar3/android-support-design/blob/master/res/layout/design_text_input_password_icon.xml#L24

**Comment by alexjlockwood** [comment]
The reason this bug occurs is because this project makes use of `AnimatedStateListDrawable` in the activity layout XML. When inflating an `AnimatedStateListDrawable` inside a layout XML file, the framework will create the animation using framework `VectorDrawable` and `AnimatedVectorDrawable`s. This is not great, because the support library `VectorDrawableCompat` and `AnimatedVectorDrawableCompat` classes fix some important bugs that are present in API 21-23.

What you could do instead is create the `AnimatedStateListDrawable` programatically. For example, in the `CheckableActivity`'s `onCreate()` method, you could construct the expand/collapse `AnimatedStateListDrawable` like this:

```
final AnimatedStateListDrawable asld = new AnimatedStateListDrawable();
asld.addState(
    new int[]{android.R.attr.state_checked},
    AppCompatResources.getDrawable(this, R.drawable.vd_checkable_expandcollapse_expanded),
    R.id.expanded);
asld.addState(
    new int[]{},
    AppCompatResources.getDrawable(this, R.drawable.vd_checkable_expandcollapse_collapsed),
    R.id.collapsed);
asld.addTransition(
    R.id.expanded,
    R.id.collapsed,
    (AnimatedVectorDrawableCompat)
        AppCompatResources.getDrawable(
            this, R.drawable.avd_checkable_expandcollapse_expanded_to_collapsed),
    false);
asld.addTransition(
    R.id.collapsed,
    R.id.expanded,
    (AnimatedVectorDrawableCompat)
        AppCompatResources.getDrawable(
            this, R.drawable.avd_checkable_expandcollapse_collapsed_to_expanded),
    false);
expandCollapseView.setImageDrawable(asld);
```

Eventually I hope that the support library will provide a compat-version of `AnimatedStateListDrawable` that will ensure this happens by default (and that also provides backwards compatibility for pre-API-21 devices). Until then... this is probably the best option you got.

I'm considering bumping the `minSdkVersion` of this project to `24` because this issue kind of makes many of these animations unusable in API 21-23. :/
